name: flutter_sample_custom_switch
description: "Custom switch sample project"
publish_to: 'none'
version: 1.0.0+1

environment: { sdk: ^3.2.6 }

dependencies:
  flutter: { sdk: flutter }
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
